# commit to be tagged for the new release
commit = "HEAD"

project_name = "Omni"
github_repo = "siderolabs/omni"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

pre_release = true
previous = "v0.38.0"

[notes]

  [notes.exposed-services]
    title = "Exposed Services Reliability"
    description = """\
Exposed services proxy now provides more reliable connection to the underlying services for slower networks in the cluster.
Also if some nodes are down the proxy will evict them from the routing.
"""
  
  [notes.equinix-metal]
    title = "Equinix Metal"
    description = """\
Equinix metal is now available as a download/PXE option in the UI/CLI.
"""

  [notes.insecure-access]
    title = "Insecure Node Access"
    description = """\
It is now possible to access nodes running in maintenance mode using `talosctl`.
Omni account wide `talosconfig` and at least `Operator` user role is required for that.
No `--insecure` flag should be set.
"""

  [notes.maintenance-talos-updates]
    title = "Maintenance Talos Updates"
    description = """\
Machine's Talos version can now be updated without adding the machine to a cluster.
Either `talosctl upgrade -n <uuid>` or the UI (Machines page) can be used for that.
"""
